### ISSUE TITLE
报错No module named 'EyeTracker'该如何解决

### ISSUE THREAD

**Issue by Tavis-design** [LiuQingSong-cell/Tobii5_EyeTracker#1]

**Comment by LiuQingSong-cell** [comment]
EyeTracker是一个通过c++代码编译得来的python库文件。你可以了解下如何将c++代码编译打包成python库，然后尝试自己编译cpp_code_for_python文件夹下的c++代码。我这里使用的方式是通过cpp_code_for_python文件夹下的setup.py文件将c++代码编译成python可使用的库文件。

**Comment by Tavis-design** [comment]
尊敬的作者您好
       我有看到在您给的文件中cpp_code_for_python文件夹有一个名为EyeTracker.cp310-win32.pyd，这个是您说的库文件吗？可以直接使用吗？我在终端尝试使用python setup.py build_ext --inplace命令的时候产生了下图的报错，麻烦您解答
![微信截图_20241124153137](https://github.com/user-attachments/assets/7e00cf2c-c098-4217-962e-c4d21221d97f)

**Comment by LiuQingSong-cell** [comment]
看你的图中貌似使用了64位的c++编译器，请使用32位编译器尝试一下，该Tobii SDK只支持32位环境

**Comment by Tavis-design** [comment]
![image](https://github.com/user-attachments/assets/76f1ee5d-3f98-47bf-8cec-06ffe81729c0)
现在说是找不到指定的模块，我不是计算机专业的，我想是不是我哪步操作有问题，能不能劳烦您指导一下，我会给您支付一定的咨询费用，如果可以的话请您添加我的微信：wxzhcdx20-6w

**Comment by LiuQingSong-cell** [comment]
这个问题是由于一个叫做PyQt的GUI框架导致的，看报错信息可能是没有正确安装，这种问题一般都是比较好解决的，请确保您已经正确安装PyQt5，如果已经安装正常来说是可以运行的。

1. 使用 pip list 查看是否安装
![1732439450357](https://github.com/user-attachments/assets/a9de86e0-9fe0-4cf0-a9e2-e81a7c18ffbd)
2. 使用 pip install PyQt5命令安装PyQt框架

**Comment by Tavis-design** [comment]
您好，我的pyqt正常安装了
![image](https://github.com/user-attachments/assets/79a087c6-a620-48e8-b145-289e60805c26)

**Comment by Tavis-design** [comment]
我尝试卸载了再装了一遍，还是如下图报错，您能帮我看看吗
![image](https://github.com/user-attachments/assets/b34a8ca7-2fde-44d5-918e-9b1c1a230f1f)

**Comment by LiuQingSong-cell** [comment]
这个问题大概率是库没正确安装。看你使用了conda下虚拟的Python解释器，请确保该解释器下安装了pyqt库。

**Comment by Tavis-design** [comment]
您好 现在报了这样的错误，不知道该如何解决了，可以麻烦您帮我看看吗

![image](https://github.com/user-attachments/assets/bd841a56-2b6c-419e-a84e-5bf4ef51d439)

**Comment by LiuQingSong-cell** [comment]
请使用32位的Python解释器试一下

**Comment by Tavis-design** [comment]
![image](https://github.com/user-attachments/assets/4f435a50-5a92-47a1-b52c-7ab6f8935b40)
您好 我是用的就是32位的解释器

**Comment by LiuQingSong-cell** [comment]
你好，这个问题我也不清楚具体原因，猜测可能是兼容性或者缺少一些Tobii SDK组件的原因，在我原来的电脑上是可以正常运行的，但中间电脑更换所有数据都不在了，也无法定位。
如果你需要采集数据，可以尝试向tobii公司索要相关的sdk，然后使用sdk编写程序进行采集，也可以参考这个项目的代码，将原始的sdk封装成一个有界面的数据采集程序。

Tobii SDK获取可以到这个网站上找一下：https://developer.tobii.com/
